version: 0.2

phases:
  build:
    commands:
      - n 12
      - npm test
      - aws s3 cp output/device-identification-data.json s3://itv-cdn-fronted/device-identification-data/data.json --cache-control max-age=60 --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
      - aws sts assume-role --role-arn $BUCKET_UPLOAD_ROLE_ARN --role-session-name codebuild-session > credentials.json
      - export AWS_ACCESS_KEY_ID=$(cat credentials.json | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(cat credentials.json | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(cat credentials.json | jq -r .Credentials.SessionToken)
      - export AWS_REGION=eu-west-1
      - aws s3 cp output/device-identification-data.json s3://$BUCKET_NAME/device-identification-data/data.json --cache-control max-age=60
artifacts:
  files: "**/*"
