version: 0.2

phases:
  build:
    commands:
      - n 12
      - npm test
      - aws sts assume-role --role-arn $BUCKET_UPLOAD_ROLE_ARN --role-session-name codebuild-session > credentials.json
      - export AWS_ACCESS_KEY_ID=$(cat credentials.json | jq -r .accessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(cat credentials.json | jq -r .secretAccessKey)
      - export AWS_SESSION_TOKEN=$(cat credentials.json | jq -r .sessionToken)
      - export AWS_REGION=eu-west-1
      - aws s3 cp output/device-identification-data.json s3://$BUCKET_NAME/device-identification-data/data.json --cache-control max-age=60
artifacts:
  files: "**/*"
