version: 0.2

phases:
  build:
    commands:
      - n 12
      - npm test
      - aws s3 cp output/device-identification-data.json s3://$BUCKET_NAME/device-identification-data/data.json --cache-control max-age=60
artifacts:
  files: "**/*"
