Description: Defines S3 infrastructure for device-identification-data
Parameters:
  DevelopmentAccount:
    Type: String
    Default: 119990297419
  ProductionAccount:
    Type: String
    Default: 198243407611
  PipelineAccount:
    Type: String
    Default: 979446310614
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      MetricsConfigurations:
        - Id: MonitorEntireBucket
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Principal:
              AWS:
                - !Ref DevelopmentAccount
                - !Ref ProductionAccount
            Condition:
              ForAnyValue:ArnLike:
                aws:PrincipalArn:
                  - "arn:aws:iam::119990297419:role/test-matterhorn-main-ComponentRole-*"
                  - "arn:aws:iam::198243407611:role/live-matterhorn-main-ComponentRole-*"
            Action:
              - s3:GetObject
            Resource:
              - !Sub "${Bucket.Arn}/*"
            Effect: Allow
          - Principal:
              AWS:
                - !Ref PipelineAccount
            Action:
              - s3:PutObject
              - s3:PutObjectAcl
            Resource:
              - !Sub "${Bucket.Arn}/*"
            Effect: Allow
  BucketUploadRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                - 979446310614
      RoleName: device-identification-data-bucket-upload-role
      Policies:
        - PolicyName: bucket-upload-policy
          PolicyDocument:
            Statement:
              - Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource:
                  - !Sub "${Bucket.Arn}/*"
                Effect: Allow
